#!/usr/bin/env php
<?php

use Calcinai\Strut\Swagger;
use Calcinai\XeroPHP\Generator\Generator;

include __DIR__.'/../vendor/autoload.php';

$schema_root = 'https://raw.githubusercontent.com/calcinai/xero-schemas/master/schemas';
$schema_files = [
    'Accounting' => 'accounting.json',
//    'PayrollAU' => 'payroll_au.json',
//    'PayrollUS' => 'payroll_us.json',
//    'Files' => 'files.json',
//    'Assets' => 'assets.json'
];

$generator = new Generator(__DIR__.'/../src/Models', 'Calcinai\\XeroPHP\\Models');

foreach($schema_files as $namespace => $schema_file){

    $schema_data = json_decode(file_get_contents(sprintf('%s/%s', $schema_root, $schema_file)));
    $schema = Swagger::create($schema_data);

    $generator->generate($namespace, $schema);

}